name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: ðŸ›Ž Check out main
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.REPO_ORG }}/${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 1
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir HB3_MAIN
          mkdir HB3_REPO
          move HB3_MAIN.7z .\HB3_MAIN\HB3_MAIN.7z
          cd HB3_MAIN
          7z  x -p${{ secrets.ZIP_PASS }} HB3_MAIN.7z
          del 950_RUN.bat
          copy .\900_CONFIG\workerTest.bat .\950_RUN.bat
          dir
          .\950_RUN.bat
