name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Run a multi-line script1
        run: mkdir TEST
      - name: Run a multi-line script2
        run: dir
      - name: Run a multi-line script3
        run: cd test
      - name: Run a multi-line script4
        run: dir
